// This file is automatically generated. Do not edit it directly.
import { createClient } from "@supabase/supabase-js";
import type { Database } from "./types";

const SUPABASE_URL = "https://nxnejhskwieaclwtjbnf.supabase.co";
const SUPABASE_PUBLISHABLE_KEY =
  "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im54bmVqaHNrd2llYWNsd3RqYm5mIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDcyMTA2ODgsImV4cCI6MjA2Mjc4NjY4OH0.FpeHl_p4AL8QbfmeBQLJWjgmHexpXU0A9yYvTsT4wds";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(
  SUPABASE_URL,
  SUPABASE_PUBLISHABLE_KEY
);
